# SQLite version 3.x
#   gem install postgresql
development:
  adapter: postgresql
  encoding: utf8
  database: TestRest2_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: TestRest2_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: TestRest2_production
  pool: 5
  username: 
  password:

#   adapter: postgresql
 # encoding: unicode