# SQLite version 3.x
#   gem install postgresql
development:
  adapter: sqlite3
  encoding: utf8
  database: TestRest2_development
  pool: 5
  username: 
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: TestRest2_test
  pool: 5
  username: 
  password:

production: 
  encoding: unicode
  adapter: postgresql
  username: rulhqmwgee
  port: 5432
  host: gB3B2oPPP3XTQRaEOQDO
  database: ec2-107-20-227-173.compute-1.amazonaws.com
  password: rulhqmwgee
  
  
# "postgres://rulhqmwgee:gB3B2oPPP3XTQRaEOQDO@ec2-107-20-227-173.compute-1.amazonaws.com/rulhqmwgee"
#   adapter: postgresql
 # encoding: unicode